taskmanager/tasks/urls.py
"""Tasks URL Configuration."""
from django.urls import path
from django.urls.conf import include

from taskmanager.tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='index'),

    path('tasks/', include([
        path('', views.TaskListView.as_view(), name='index'),
        path('create/', views.TaskCreateView.as_view(), name='create'),
        path('<int:pk>/', include([
            path('', views.TaskDetailView.as_view(), name='detail'),
            path('edit/', views.TaskUpdateView.as_view(), name='edit'),
            path('delete/', views.TaskDeleteView.as_view(), name='delete'),
        ])),
    ])),

    path('task-status/', include([
        path('', views.TaskStatusListView.as_view(), name='status-list'),
        path(
            'create/',
            views.TaskStatusCreateView.as_view(),
            name='status-create',
        ),
        path('<int:pk>/', include([
            path(
                '',
                views.TaskStatusDetailView.as_view(),
                name='status-detail',
            ),
            path(
                'edit/',
                views.TaskStatusUpdateView.as_view(),
                name='status-edit',
            ),
            path(
                'delete/',
                views.TaskStatusDeleteView.as_view(),
                name='status-delete',
            ),
        ])),
    ])),
]

taskmanager/urls.py
"""Taskmanager URL Configuration."""

from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path

urlpatterns = [
    path('', include('taskmanager.tasks.urls')),
    path('auth/login', views.LoginView.as_view(), name='login'),
    path('auth/logout', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

taskmanager/tasks/models.py
"""Models for tasks app."""
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=120, unique=True) # noqa WPS432

    def __str__(self):
        return '{name}'.format(name=self.name)

    class Meta:
        ordering = ['name']


class TaskStatus(models.Model):
    name = models.CharField(max_length=120, unique=True) # noqa WPS432

    def __str__(self):
        return '{name}'.format(name=self.name)

    def get_absolute_url(self):
        return reverse('tasks:status-detail', args=[self.pk])


class Task(models.Model):
    name = models.CharField(max_length=120) # noqa WPS432
    description = models.TextField(blank=True, null=True)
    status = models.ForeignKey(TaskStatus, default=1, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    creator = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='creator',
    )
    assigned_to = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name='assigned_to',
    )
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return '{name} ({id})'.format(name=self.name, id=self.id)

    def tags_to_string(self):
        return ', '.join(tag.name for tag in self.tags.all())

    def get_absolute_url(self):
        return reverse('tasks:detail', args=[self.pk])

taskmanager/tasks/views.py
"""Views for tasks app."""
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django_filters.views import FilterView  # type: ignore

from taskmanager.tasks.filters import TaskFilter
from taskmanager.tasks.models import Task, TaskStatus


class TaskListView(FilterView):
    filterset_class = TaskFilter
    ordering = ('-created_at',)


class TaskDetailView(DetailView):
    model = Task


class TaskCreateView(CreateView):
    model = Task
    fields = ('name', 'description', 'assigned_to', 'status', 'tags')

    def form_valid(self, form):
        task = form.save(commit=False)
        task.creator = self.request.user
        return super().form_valid(form)


class TaskUpdateView(UpdateView):
    model = Task
    fields = ('name', 'description', 'assigned_to', 'status', 'tags')


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:index')


class TaskStatusListView(ListView):
    model = TaskStatus
    ordering = ('id',)


class TaskStatusDetailView(DetailView):
    model = TaskStatus


class TaskStatusCreateView(CreateView):
    model = TaskStatus
    fields = ('name',)


class TaskStatusUpdateView(UpdateView):
    model = TaskStatus
    fields = ('name',)


class TaskStatusDeleteView(DeleteView):
    model = TaskStatus
    success_url = reverse_lazy('tasks:status-list')

taskmanager/tasks/templates/_base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}{% endblock %}</title>
    {% bootstrap_css %}
  </head>
  <body>
    {% bootstrap_messages %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">Navbar</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input
            class="form-control mr-sm-2"
            type="text"
            placeholder="Search"
            aria-label="Search"
          />
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">
            Search
          </button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      {% block content %}{% endblock %}
    </main>
    {% bootstrap_javascript jquery='full' %}
  </body>
</html>

taskmanager/tasks/templates/tasks/home.html
{% extends '_base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Home</h1>
{% endblock %}

taskmanager/templates/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Taskmanager{% endblock %}</title>
    {% bootstrap_css %}
  </head>
  <body>
    {% bootstrap_messages %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="/">Taskmanager</a>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">
              Logout ({{ user.username }})
            </a>
          {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          {% endif %}
        </li>
      </ul>
    </nav>

    <main role="main" class="container">
      {% load django_bootstrap_breadcrumbs %}

      {% block breadcrumbs %}
          {% clear_breadcrumbs %}
      {% endblock %}

      {% block content %}
          {% render_breadcrumbs %}
      {% endblock %}
    </main>
    {% bootstrap_javascript jquery='full' %}
  </body>
</html>

taskmanager/templates/tasks/task_confirm_delete.html
{% extends 'base.html' %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Tasks" "tasks:index" %}
    {% breadcrumb object.title "tasks:detail" object.id %}
    {% breadcrumb "Delete" "" %}
{% endblock %}

{% block content %}
    {{ block.super }}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
{% endblock %}

taskmanager/templates/tasks/task_detail.html
{% extends 'base.html' %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Tasks" "/" %}
    {% breadcrumb object.name "" %}
{% endblock %}

{% block content %}
    {{ block.super }}
    <hr>
    <div>
        <a href="{% url 'tasks:edit' object.id %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'tasks:delete' object.id %}" class="btn btn-danger">Delete</a>
    </div>
    <hr>
    <div class="row">
        <div class="col-9">
            <h1>{{ object.name }}</h1>
            <p>{{ object.description }}</p>
        </div>
        <div class="col-3">
            <div>Status: {{ object.status }}</div>
            <div>Creator: {{ object.creator }}</div>
            <div>Assigned to: {{ object.assigned_to.username }}</div>
            <div>Tags: {{ object.tags_to_string }}</div>
        </div>
    </div>
{% endblock %}

taskmanager/templates/tasks/task_filter.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
    <a href="{% url 'tasks:create' %}" class="btn btn-success">Create task</a>
    <div class="mb-4"></div>

    <form method="get" class="mb-4">
        {{ filter.form|crispy }}
        <input type="submit" class="btn btn-success" />
    </form>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Status</th>
                <th scope="col">Assigned_to</th>
                <th scope="col">Creator</th>
                <th scope="col">Created At</th>
                <th scope="col">Tags</th>
            </tr>
        </thead>
        <tbody>
            {% for task in filter.qs %}
                <tr>
                    <td><a href="{% url 'tasks:detail' task.pk %}">{{ task.name }}</a></td>
                    <td><span class="badge badge-secondary">{{ task.status }}</span></td>
                    <td>{{ task.assigned_to.username }}</td>
                    <td>{{ task.creator }}</td>
                    <td>{{ task.created_at }}</td>
                    <td>{{ task.tags_to_string }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td>No tasks yet.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

taskmanager/templates/tasks/task_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Tasks" "tasks:index" %}
    {% if object %}
        {% breadcrumb object.name "tasks:detail" object.id %}
        {% breadcrumb "Update" "" %}
    {% else %}
        {% breadcrumb "Create" "" %}
    {% endif %}
{% endblock %}

{% block content %}
    {{ block.super }}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        {% if object %}
            <button type="submit" class="btn btn-primary">Update task</button>
        {% else %}
            <button type="submit" class="btn btn-success">Create task</button>
        {% endif %}
    </form>
{% endblock %}

taskmanager/templates/tasks/task_list.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'tasks:create' %}" class="btn btn-success">Create task</a>
    <div class="mb-3"></div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Status</th>
                <th scope="col">Assigner</th>
                <th scope="col">Creator</th>
                <th scope="col">Created At</th>
                <th scope="col">Tags</th>
            </tr>
        </thead>
        <tbody>
            {% for task in object_list %}
                <tr>
                    <td><a href="{% url 'tasks:detail' task.pk %}">{{ task.title }}</a></td>
                    <td><span class="badge badge-secondary">{{ task.state }}</span></td>
                    <td>{{ task.assigner }}</td>
                    <td>{{ task.creator }}</td>
                    <td>{{ task.created_at }}</td>
                    <td>{{ task.tags_to_string }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td>No tasks yet.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

taskmanager/templates/tasks/taskstatus_confirm_delete.html
{% extends 'base.html' %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Task Status" "tasks:status-list" %}
    {% breadcrumb "Delete" "" %}
{% endblock %}

{% block content %}
    {{ block.super }}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
{% endblock %}

taskmanager/templates/tasks/taskstatus_detail.html
{% extends 'base.html' %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Task Status" "tasks:status-list" %}
    {% breadcrumb object.name "" %}
{% endblock %}

{% block content %}
    {{ block.super }}
    <hr>
    <div>
        <a href="{% url 'tasks:status-edit' object.id %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'tasks:status-delete' object.id %}" class="btn btn-danger">Delete</a>
    </div>
    <hr>
    <div class="row">
        <div class="col">
            <h1>{{ object.name }}</h1>
        </div>
    </div>
{% endblock %}

taskmanager/templates/tasks/taskstatus_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Task Status" "tasks:status-list" %}
    {% if object %}
        {% breadcrumb "Update" "" %}
    {% else %}
        {% breadcrumb "Create" "" %}
    {% endif %}
{% endblock %}

{% block content %}
    {{ block.super }}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        {% if object %}
            <button type="submit" class="btn btn-primary">Update status</button>
        {% else %}
            <button type="submit" class="btn btn-success">Create status</button>
        {% endif %}
    </form>
{% endblock %}

taskmanager/templates/tasks/taskstatus_list.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'tasks:status-create' %}" class="btn btn-success">Create status</a>
    <div class="mb-3"></div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
            </tr>
        </thead>
        <tbody>
            {% for task_status in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'tasks:status-detail' task_status.pk %}">{{ task_status.name }}</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td>No status yet.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}